### PR TITLE
Settings rework with Filter changes

### PR DESCRIPTION
**Pull request by db-2001**
Big rework for the settings popup and the filtering popup. API side does need a bit of work to be compatible for it so sorry about that, but if some of the API calls/features seem unnecessary more than happy to discuss. 

General changes: 
- Revamped the settings pop-up to be more user-friendly. It now has some resizing logic to account for different screen sizes
- Revamped the filtering function, we can now filter by connector as well as publication status in addition to title, combination of all 3 also works
- Added the manga connectors and their rate limits to the settings pop up. The enable/disable for global search can also go here in the future as well as any other connector specific features.

Settings pop-up before: 
image

Settings pop-up after: 
image

image

Filtering method before: 
image

Filtering method after: 
image

image

image

image

image

image

image

image

**Code behavior changes:** 
- Deprecated the changeStyleSheets function, this will now be stored in the browsers local storage so that different styles (more planned in future) can be set as default for different devices (mobile vs tablet vs web)

**API changes**
- Added Reset and Test POSTs to each connector with the intent that reset will remove it from Tranga's memory as if it never existed (you might be able to see that I have LunaSea configured but this was an accident on my part and cannot "undo" as sending an empty string is not allowed (for good reason)). Test would essentially do the default connector behavior (i.e send a test notification, trigger a scan in Kavita/Komga) to check that the fields are acceptable without actually saving them (allows you to verify that it is working as intended before saving). The user would have to check the connector to make sure that it actually worked, no way right now to display if test was successful or not. These need to be implemented on the API side.
- changeStyleSheets can be removed from settings
- REQUIRED: Need to add GET messages so that the rate limit for each connector can be displayed, POST is already implemented as per Server.cs syntax. (Technically untested on website-side but this is just a simple POST request so I don't forsee anything going wrong). This also needs to be then implemented on the website side.
- GET /LogFile returns a BadRequest, not sure of what is going on on the API side. Once the request behavior is fixed, some work will need to be done to make sure we can download the file from the website.
- Have confirmed that for whatever reason updating the Kavita connector does not work, perhaps this was once working and continues to work if set up but no longer allows you to set up Kavita. It looks like the POST successfully completes so I can't troubleshoot any further. Help appreciated as this is a major feature many users like.
- Might create a separate issue, but support for PushBullet as a notification connector might be nice if possible, despite not being strictly self-hosted.

Addresses #39 #10

### CODE REVIEW

**Comment by db-2001** [comment]
Would you also be able to consider if it makes sense to merge the website code with the main API code? It would get rid of the pain point for many users of specifying the API URI (since you could just point it back to itself). I don't think it'll impact the ability for other people who write their own front ends or anything to access/make changes to the API. It'll also make it easier to release changes that need both API and website updates so we don't have to coordinate making the changes and hoping nobody else pulls the repo while they're not synced up. It also might motivate me to learn C# and make the API changes myself if everything is just in one repo, lol.

**Comment by C9Glax** [comment]
Holy moly. Fkn amazing.
Okay making a PR for all the requested changes, then merging once both are ready.

[x] changeStyleSheets can be removed from settings
[ ] Added Reset and Test POSTs 
[ ] GET messages for rate limits for each connector can be displayed
[ ] @db-2001 I changed the way RequestLimits work, to just be a global Connector thing. Sorry about that, but I figured it would make things easier to configure. The different types are in [RequestType.cs](https://github.com/C9Glax/tranga/blob/0b4461265c7fcf691f215a23f00b80dc5af3d49a/Tranga/MangaConnectors/RequestType.cs)
[ ] GET /LogFile returns a BadRequest, not sure of what is going on on the API side. Once the request behavior is fixed, some work will need to be done to make sure we can download the file from the website.
[ ] Kavita https://github.com/C9Glax/tranga/issues/121

> It would get rid of the pain point for many users of specifying the API URI

Not really though, since it would still be two separate containers. Just like now.
I had them originally in one repo, but Issue tracking was a nightmare, because people were confusing what was going on where.

And as for coordinating:
> Okay making a PR for all the requested changes, then merging once both are ready.

**Comment by db-2001** [comment]
> [ ] @db-2001 I changed the way RequestLimits work, to just be a global Connector thing. Sorry about that, but I figured it would make things easier to configure. The different types are in [RequestType.cs](https://github.com/C9Glax/tranga/blob/0b4461265c7fcf691f215a23f00b80dc5af3d49a/Tranga/MangaConnectors/RequestType.cs)

No problem, so now Tranga configures (or can configure) different rate limits for images, covers, info, with additional settings specific to MangaDex? I might keep the MangaDex ones in that section but I'll move the others to the API settings section in the settings. Not sure if I should keep or get rid of the other connectors since their settings will be empty...
 
> Not really though, since it would still be two separate containers. Just like now.

I guess I'm not understanding why they'd be two separate containers, can the API web server not also host the webpage? Or can the two not live side-by-side?

I should be able to get most of these things implemented tomorrow (my time)

**Comment by C9Glax** [comment]
> No problem, so now Tranga configures (or can configure) different rate limits for images, covers, info, with additional settings specific to MangaDex?

Correct.

> I guess I'm not understanding why they'd be two separate containers, can the API web server not also host the webpage? Or can the two not live side-by-side?

Theoretically I can also write a small webserver that would serve these files. However since all javascript code is executed client-side, e.g. in the webbrowser, you would have to tell the site where to look for the api calls anyways, and just using an existing webserver solution (like nginx) makes things easier. If we were to create dynamically generated sites, that would change some things, but also make them a lot more complicated.

> how would you recommend I test with that branch? 

If you want to try to develop C# code anyways, you should get an IDE, like Visual Studio, Jetbrains Rider, or anything else. From there you can clone the repository/branch and either build/compile or just run the code in the debugger.

**Comment by db-2001** [comment]
> If you want to try to develop C# code anyways, you should get an IDE, like Visual Studio, Jetbrains Rider, or anything else. From there you can clone the repository/branch and either build/compile or just run the code in the debugger.

Yup, just installed it and cloned the repository/branch, will try it out now

**Comment by C9Glax** [comment]
Okay so I think I implemented the API calls now, haven't tested yet. If you are missing anything lmk

**Comment by db-2001** [comment]
Will do, have to figure out how to open the repo in VS and get it running first s

**Comment by db-2001** [comment]
Notes from testing: 
- Gotify, Ntfy, Kavita, and Komga don't send an HTTP response to the POST when testing the connector, only LunaSea does; don't know if this is intended behavior or not
- GET /LogFile still returns a 404 not found when looking in the console. Not sure if this is because there is an actual error or if somehow when I started the project the logger didn't start so there is no log file to return.
- GET and POST API calls for rate limits seem to be working as intended. 

Unrelated: 
I (obviously) managed to get the Tranga project in Visual Studio working, not sure how to view the logs from the Logger though. Is there anyway I can actually test that everything is running properly?

**Comment by C9Glax** [comment]
>Gotify, Ntfy, Kavita, and Komga don't send an HTTP response to the POST when testing the connector, only LunaSea does; don't know if this is intended behavior or not

They should return a ACCEPTED response... Will look into it.

> GET /LogFile still returns a 404 not found when looking in the console. Not sure if this is because there is an actual error or if somehow when I started the project the logger didn't start so there is no log file to return.

404 means there is no Logfile. You have to enable the FileLogger with `-f` as Start-Argument.

> I (obviously) managed to get the Tranga project in Visual Studio working, not sure how to view the logs from the Logger though. Is there anyway I can actually test that everything is running properly?

Same here, enable the ConsoleLogger with `-c`

**Comment by db-2001** [comment]
How do I start it from the command line? I've just been clicking the green play button in VS to start tranga.
image

**Comment by C9Glax** [comment]
I don't use Visual Studio, however https://stackoverflow.com/questions/298708/debugging-with-command-line-parameters-in-visual-studio seems that you have to right-click the "Tranga" 
image
and set it there...

**Comment by db-2001** [comment]
Ahh, thank you so much, sorry for making you check, couldn't figure out what to google

**Comment by db-2001** [comment]
Got logs to download successfully. I think that's everything from my end?

**Comment by C9Glax** [comment]
Yup everything else is API-sided.
Just the POST-return on the /Test Endpoints and checking why Kavita isn't updating.

**Comment by db-2001** [comment]
I plan on using my self-hosted Vikunja instance to keep track of development items: https://vikunja.abhatnagar.org/share/ukTdOrlvXOd2u0THmuW3WqIVgtahtvOgWdUF24Wq/auth?view=kanban

That link will only let you view the board, but if you're interested in collaborating using it, then you're more than welcome to create an account and then I can add you to the project :)

**Comment by C9Glax** [comment]
Good idea! Github has it's own Kanban board in Projects. I just added you, moving all your items over right now :)

**Comment by db-2001** [comment]
Awesome! It looks great! Should I continue to make changes in the future on my own repositories like I have been or create branches in the main one?

**Comment by C9Glax** [comment]
You should be able to link your own repos in there, so do that!

**Comment by C9Glax** [comment]
Okay unless I am missing something I think everything should be implemented and working with the rework.
lmk if you have anything, if not i am going to merge :)

**Comment by db-2001** [comment]
Looks good on my end

**Comment by C9Glax** [comment]
Okay merging and praying we don't break anything 🙏🏼

**Pull request merged**
