### PR TITLE
Update btn fix

### PR DESCRIPTION
**Pull request by db-2001**
Addresses #18

### CODE REVIEW

**Comment by db-2001** [comment]
This fixes the update button but when adding a new manga (or removing one), the manga library view doesn't automatically refresh even though RefreshContent() is called. Not sure if I added it to the right spot, but will continue to debug.

**Comment by C9Glax** [comment]
Okay, here is another git-thing:
As you can see, all your previous commits are also included, which are entirely unrelated.
That is why you normally (and I am also guilty of this) develop new features and fixes on seperate branches.
So you would fork your master branch (before any changes) `git branch <newFeatureName>` and then create a PR for that branch.
This way you can develop multiple features at once, without breaking production.

So the way to do this now, after the fact:
1. Checkout the master-branch before all changes (https://github.com/db-2001/tranga-website/commit/f6544e743b84ac468ef7fa22c9a1ca75eff6f361) this commit
2. Create the new branch
3. Re-apply the changes to this new branch

**Comment by dityb** [comment]
Gotcha, yeah I'll do that. I was working under the assumption that the other PR would be merged in before this one so it wouldn't have too much of an effect.

**Comment by db-2001** [comment]
Gotcha, yeah that makes sense, I can do that. I was working under the assumption that the other PR would be merged in before this one so it wouldn't end up making a difference.

**Pull request closed without merging**
