### PR TITLE
Latest Chapter Downloaded/Available Indicator

### PR DESCRIPTION
**Pull request by db-2001**
Adds a feature that shows the latest chapter downloaded, in the default library view, or the latest chapter available, from the search menu. The latest chapter downloaded shows up as white text on a green background and the latest available chapter from a connector shows up as white text on a blue background.

image
image

Currently, the display style has been set to none so that the feature is hidden until the API is ready for it, but the JS script code makes an important assumption: 
image

This was the only way I could get the one common JS function to return the correct value/color combo without having to add an indication of where the function was called from. If there's a better way to implement the logic for this then I'm all ears.

### CODE REVIEW

**Comment by C9Glax** [comment]
Looks good!

> Currently, the display style has been set to none so that the feature is hidden until the API is ready for it

You mean until the api reports what is on disk? (e.g. which files actually exist)

**Comment by db-2001** [comment]
Yeah that's what I meant

**Comment by db-2001** [comment]
@C9Glax any updates on finishing the implementation on the API side? i was thinking that the publication status indicator could be rolled into this as well, just by changing the background color of the chapter number, I don't know why I insisted on having the search chapter number be a different color. Right now it makes more sense for both the library view and the manga search to have the same chapter number coloring corresponding to publication status but let me know what you think

**Comment by C9Glax** [comment]
Haven't worked on Tranga in a minute apart from some bug fixes...
Exams hitting :)

**Comment by db-2001** [comment]
Totally understand, no worries!

**Comment by db-2001** [comment]
Branch is too out-of-date for current and planned changes, will re-implement better with the publication status indicator rolled in at some later date.

**Pull request closed without merging**
