### PR TITLE
Initial feature for Publication Status Indicator

### PR DESCRIPTION
**Pull request by db-2001**
Addresses #25 

Adds a small circular indicator next to the manga title indicating release status: 
image

Includes a tooltip on hover
image
image
image
image

### CODE REVIEW

**Comment by db-2001** [comment]
Obviously this doesn't work on mangas already that are in the library because their metadata needs to be refetched

**Comment by db-2001** [comment]
I did put an indicator in for "Status Unavailable" which shows up as grey so that could be -1 or something on the API side that is the default for everything until the official status' get fetched and matched to something that's represented.

**Comment by C9Glax** [comment]
Atm default is OnHiatus.
I have already done some work on an UpdateMetadata Job, but I haven't done any testing yet.

https://github.com/C9Glax/tranga/commit/4843c7f05c904736aa3ab5436b90712baed899b9
https://github.com/C9Glax/tranga/commit/963ad375e8b9b036cb8b3337ab7c41dfe8da5499

**Comment by db-2001** [comment]
Ok, that works, either way this is ready to be merged in whenever you feel like it, whether you want to do it now or wait until the update metadata is done. Do you want me to add a button to update metadata to link it with a job?

**Comment by C9Glax** [comment]
If you can add a button that triggers an API request `POST /Jobs/UpdateMetadata` with optional parameters to for example update a specific manga...
Could also just trigger an update for all manga

**Comment by db-2001** [comment]
Sure thing, what does the post syntax look like for updating all vs updating a specific one? I'm thinking update all could be a button in settings and updating a specific one could be a button in each manga's popup

**Comment by C9Glax** [comment]
Updating all would be `POST /Jobs/UpdateMetadata`
Updating specific one would be `POST /Jobs/UpdateMetadata?internalId=<mangaId>`
You can get the id from the publication that was clicked on. `selectedManga` is updated accordingly
grafik


Design sounds good!

**Pull request merged**
