### PR TITLE
Ability to override defaultApiUrl

### PR DESCRIPTION
**Pull request by vonProteus**
When deploying in Kubernetes, you can override `defaultApiUri.js` with the following code:
```javascript
let apiUri = `https://tranga.lan/api/`;
```
This way, when you first access the site, there's no need to manually update the API endpoint in the settings.

### CODE REVIEW

**Comment by vonProteus** [comment]
can you show me how?
or link issue

I use traefik and k8s if that makes any difference

**Comment by db-2001** [comment]
Maybe some differences there then but for the tranga-website docker image, go to the code for the cuttingedge or dev branches (mis remembered that it was on all branches) and you'll see an nginx folder that has a template file to proxy pass /API/ to the API URL.

The tranga-website webserver is nginx, it shouldn't matter what reverse proxy you're putting in front of it, whether that's caddy, traefik, or npm

**Comment by vonProteus** [comment]
Upon reviewing my commit, you can see that the only change made is the relocation of the following line:
```JavaScript
let apiUri = `${window.location.protocol}//${window.location.host.split(':')[0]}:6531`
```
This line has been moved to a new file: [Website/defaultApiUri.js](https://github.com/C9Glax/tranga-website/pull/117/files#diff-bf774412cc5d9cc5813c8154209d07b57cf1039f38c7050b5c821203fd9ccf05)
I plan to override this in my Kubernetes configuration with the following code:
```JavaScript
let apiUri = `https://tranga.lan/api/`
```
In essence, this change does not alter the current behavior of the application; it simply introduces the ability to override the default API URL in Kubernetes or Docker environments.

**Comment by vonProteus** [comment]
Can you merge it or propose a better solution?

**Pull request merged**
